AWS_ACCESS_KEY = "AKIAJF32NFXTCPXXNFHQ"
AWS_SECRET_KEY = "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"

#Remote
POSTGRES_HOST = 'jobs-meta.c3av43lgatyh.us-east-1.rds.amazonaws.com'
POSTGRES_USERNAME = 'aemadmin'
POSTGRES_PASSWORD = 'fj38f*l)3$'
POSTGRES_PORT = 5432
POSTGRES_DBNAME = 'jobs'
SECRET_KEY = '8+?LYi;kz&yDu^5'

#Local
POSTGRES_HOST_LOCAL = 'localhost'
POSTGRES_USERNAME_LOCAL = 'alexemorris'
POSTGRES_PASSWORD_LOCAL = 'fj38f*l)3$'



