AWS_ACCESS_KEY = "AKIAIIZXGLXXQ36NZWJQ"
AWS_SECRET_KEY = "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"

#Remote
POSTGRES_HOST = 'jobs-meta.c3av43lgatyh.us-east-1.rds.amazonaws.com'
POSTGRES_USERNAME = 'aemadmin'
POSTGRES_PASSWORD = 'fj49f*a)2£'
POSTGRES_PORT = 5432
POSTGRES_DBNAME = 'jobs'
SECRET_KEY = '8+?LYi;kz&yDu^5'

#Local
POSTGRES_HOST_LOCAL = 'localhost'
POSTGRES_USERNAME_LOCAL = 'alexemorris'
POSTGRES_PASSWORD_LOCAL = 'fj38f*l)3$'



